revChatGPT/Exceptions.py,sha256=70Dmggf9AQGBKnfg0NJJmyKugBUig42THIs6OD5jeMA,632
revChatGPT/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
revChatGPT/__main__.py,sha256=aqn8OiWA5zaZF0cvcxiGArirsjtAZwEPSy0F4eDWGA0,5759
revChatGPT/revChatGPT.py,sha256=H8r8OFl3Ra1jWV3qOlfjDPe9zqiZ05OoojxwlHHlHa0,19647
revChatGPT-0.0.38.5.dist-info/LICENSE,sha256=gXf5dRMhNSbfLPYYTY_5hsZ1r7UU1OaKQEAQUhuIBkM,18092
revChatGPT-0.0.38.5.dist-info/METADATA,sha256=-FVFTIXeLwLwyiNMYfDcDBoCsrJIVeml-YBXU1pTNvA,2495
revChatGPT-0.0.38.5.dist-info/WHEEL,sha256=2wepM1nk4DS4eFpYrW1TTqPcoGNfHhhO_i5m4cOimbo,92
revChatGPT-0.0.38.5.dist-info/entry_points.txt,sha256=XWRsRhbycEK0s0FlJsWUcWPSuZ5Gr0InFuJdEiKeUiE,56
revChatGPT-0.0.38.5.dist-info/top_level.txt,sha256=6O3ay3adff-Qrq0tGYaEe_XXhvCZ5vGC9AshCmZzRMA,11
revChatGPT-0.0.38.5.dist-info/RECORD,,
