class TaskAlreadyExists(Exception):
    """Function already exists in task mapper"""


class TaskNotExists(Exception):
    """No such task in map"""
